services:
  mysql:
    image: mysql:9.4.0
    container_name: pizza-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PizzaDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--bind-address=0.0.0.0"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: pizza-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=PizzaDb;User=root;Password=rootpassword;"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: